name: Pull from Gitee

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜（UTC时间）运行
  workflow_dispatch:  # 添加手动触发事件

jobs:
  pull:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write  # 添加工作流权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "pridejoy@foxmail.com"
          git config --global user.name "Malus"

      - name: Pull from Gitee
        run: |
          git remote add gitee https://gitee.com/Pridejoy/MalusAdmin.git
          git fetch gitee master
          git reset --hard gitee/master
          git push origin master --force
